spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec202110c
    username: postgres
    password: postgres
  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ec.202110c@gmail.com
#    password: test&ec202110c
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true
    host: localhost
    port: 1025
server:
  servlet:
    context-path: /ec-202110c
